apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mynginx
  namespace: default
spec:
  template:
    metadata:
      labels:
        app: mynginx
    spec:
      containers:
      - image: dongyali521521/mynginx:<BUILD_TAG>
        imagePullPolicy: IfNotPresent
        name: mynginx
